import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Provider from '@/app/context/AuthContext'
import ToasterContext from '@/app/context/ToasterContext'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <ToasterContext />
          {children}
        </Provider></body>
    </html>
  )
}
